### ISSUE TITLE
Image on docker hub

### ISSUE THREAD

**Issue by shoetten** [pretalx/pretalx-docker#25]
Hey @rixx,
thank you for this awesome project! Up until now i was using your [docker hub image](https://hub.docker.com/r/pretalx/standalone) for my self hosted instance. Do you plan on updating that or should i start maintaining my own image again?

Thanks again!

**Comment by rixx** [comment]
Hi @shoetten, and thanks for reaching out! pretalx-docker isn't officially supported and I don't always have the time or energy to look after it, beyond updating this repository. Could I interest you in becoming part of the pretalx team on Dockerhub and getting permissions to this repo, so that you can push an image if I forget?

As for this time, I forgot to tag the new commit (tags trigger auto-builds on Dockerhub). And when I belatedly tagged it, it turns out that the GitHub connection had expired. I have re-linked GitHub and both builds (2.0.0 and 2.1.1) are now running.

**Comment by shoetten** [comment]
Hey @rixx, awesome, thank you! Just upgraded and after a quick `pretalx regenerate_css` everything looks awesome.
Yes, i could image maintaining this image on a minimal sort of basis. Meaning, i don't have time to put a lot of work into it, but i could do a little bit of work here and there and could bump new releases, if you don't get to it. If that sounds good to you, feel free to grant me access to this repo & docker hub (same username as on github).

**Comment by rixx** [comment]
I added you to this repo – that should be enough for now, since a new tag will trigger a dockerhub build (and I'm afraid the pretalx org on dockerhub uses my own GitHub OAuth for sync, so I should figure out a new one before granting people access :D). Thank you!

**Comment by shoetten** [comment]
Haha, alright :)
