### ISSUE TITLE
Dockerfile does not work with pretalx v2023.1.0

### ISSUE THREAD

**Issue by rixx** [pretalx/pretalx-docker#45]
The new pretalx version has a new install path (which I fixed in the Dockerfile), and also requires npm/nodejs. As this repository is community-maintained, somebody would need to fix the missing dependencies and check that the Dockerfile is otherwise still up to date. Current errors can be seen [here in the build log](https://github.com/pretalx/pretalx-docker/actions/runs/6065744137/job/16455593081).

Once that's done and merged, I'll look into triggering a new push to Dockerhub via this repo's GitHub Actions.

**Comment by saschafoerster** [comment]
I have the same error and I am a bit stuck here.

**Comment by ketsapiwiq** [comment]
Hi, just created a PR for this: https://github.com/pretalx/pretalx-docker/pull/47
I'm adding nodejs, (re)building, then deleting it. If you don't do that you double the Docker image.
I don't like chaining instructions like this but that's what Docker pushes you to do.
Otherwise you use multi-stage build which could be quite elegant but I ended up getting fed up on not being able to "squash" two images.
Other thing: is it problematic if I upgrade the base image to Debian Bookworm? It makes installing (then removing) Nodejs version 18 a breeze.

**Comment by rixx** [comment]
I have no opinion on Debian or Docker at all, so if changing the Debian version makes maintaining the image easier, please go for it! I'll hold off merging the PR till then, I'm guessing?

**Comment by saschafoerster** [comment]
Upgrading with v2023.1.3  worked.
