### ISSUE TITLE
Rerun workflow to build 2024.1.0 containers

### ISSUE THREAD

**Issue by Shuttleu** [pretalx/pretalx-docker#58]
So there appears to be an issue with Github workflows, re-runs of the same code should produce the same results, however it seems the workflow is getting stuck on the arm64 build of the container.

Re-running the workflow a few times seems to allow it to progress (even though this shouldn't happen)

[This run](https://github.com/Shuttleu/pretalx-docker/actions/runs/8213415088) (fresh fork of the repo with no changes) has got stuck on the arm64 build when it gets to `pretalx rebuild`
[This run](https://github.com/Shuttleu/pretalx-docker/actions/runs/8213846493) (the exact same code) has passed after being run 4 times.

Im not sure what is causing the build to hang and I'm not sure how I would go about investigating it, however it seems that re-running the build a few times seems to allow it to build successfully.

**Comment by rixx** [comment]
I started a re-run [10 minutes before you opened this issue](https://github.com/pretalx/pretalx-docker/actions/runs/7931838612), which has now passed. As always, I'm happy for offers of

a) PRs that fix this issue, or
b) people interested in maintaining this repo, as it's intended to be community-maintained (because I have no knowledge of or interest in Docker at all).
